# Generated by Django 4.2.21 on 2025-05-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.RenameField(
            model_name='incomingorder',
            old_name='availableQuantity',
            new_name='quantityToSupply',
        ),
        migrations.RemoveField(
            model_name='incomingorder',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='incomingorder',
            name='supplierId',
        ),
        migrations.AlterField(
            model_name='outgoingorder',
            name='customerId',
            field=models.ManyToManyField(to='inventoryapp.customer'),
        ),
        migrations.AddField(
            model_name='incomingorder',
            name='productId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='incomingorder', to='inventoryapp.product'),
        ),
        migrations.AddField(
            model_name='incomingorder',
            name='supplierId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='incomingorder', to='inventoryapp.supplier'),
        ),
    ]
