# Generated by Django 4.2.21 on 2025-05-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='availableQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='totalPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unitPrice',
            field=models.FloatField(default=0),
        ),
    ]
