# Generated by Django 4.2.21 on 2025-05-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_remove_product_price_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingorder',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='outgoingorder',
            name='productId',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='outgoingorder',
            name='customerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='outgoingorder', to='inventoryapp.customer'),
        ),
        migrations.AddField(
            model_name='outgoingorder',
            name='productId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='outgoingorder', to='inventoryapp.product'),
        ),
    ]
